<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta http-equiv="ClearType" content="true">
  <meta http-equiv="X-UA-Compatible" content="chrome=1" />
  <title>Star of the West Archive</title>

  <link href="stylesheets/DV/components/reset.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/structure.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/ui.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/annotations.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/pages.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/ui-header.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/ui-footer.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/ui-menu.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/ui-navigation.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/ui-search.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/ui-text.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/ui-zoom.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/view-annotations.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/view-document.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/view-search.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/view-text.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/view-thumbnails.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/unsupported.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/components/minimode.css" media="screen" rel="stylesheet" type="text/css" />
  <link href="stylesheets/DV/themes/plain.css" media="screen" rel="stylesheet" type="text/css" />

  <link href="stylesheets/DV/print.css" media="print" rel="stylesheet" type="text/css" />

  <style>
    body { margin: 10; }
  </style>

<script src="javascripts/DV/vendor/jquery-1.5.1.js" type="text/javascript"></script>
<script src="javascripts/DV/vendor/jquery-ui-1.8.1.custom.min.js" type="text/javascript"></script>
<script src="javascripts/DV/vendor/underscore.js" type="text/javascript"></script>
<script src="javascripts/DV/vendor/jquery.acceptInput.js" type="text/javascript"></script>
<script src="javascripts/DV/vendor/jquery.placeholder.js" type="text/javascript"></script>
<script src="javascripts/DV/lib/initializer.js" type="text/javascript"></script>
<script src="javascripts/DV/lib/history.js" type="text/javascript"></script>
<script src="javascripts/DV/lib/annotation.js" type="text/javascript"></script>
<script src="javascripts/DV/lib/drag_reporter.js" type="text/javascript"></script>
<script src="javascripts/DV/lib/elements.js" type="text/javascript"></script>
<script src="javascripts/DV/lib/page.js" type="text/javascript"></script>
<script src="javascripts/DV/lib/page_set.js" type="text/javascript"></script>
<script src="javascripts/DV/lib/thumbnails.js" type="text/javascript"></script>
<script src="javascripts/DV/schema/schema.js" type="text/javascript"></script>
<script src="javascripts/DV/elements/elements.js" type="text/javascript"></script>
<script src="javascripts/DV/models/annotation.js" type="text/javascript"></script>
<script src="javascripts/DV/models/chapter.js" type="text/javascript"></script>
<script src="javascripts/DV/models/document.js" type="text/javascript"></script>
<script src="javascripts/DV/models/page.js" type="text/javascript"></script>
<script src="javascripts/DV/events/events.js" type="text/javascript"></script>
<script src="javascripts/DV/events/ViewAnnotation.js" type="text/javascript"></script>
<script src="javascripts/DV/events/ViewDocument.js" type="text/javascript"></script>
<script src="javascripts/DV/events/ViewSearch.js" type="text/javascript"></script>
<script src="javascripts/DV/events/ViewText.js" type="text/javascript"></script>
<script src="javascripts/DV/events/ViewThumbnails.js" type="text/javascript"></script>
<script src="javascripts/DV/events/history.js" type="text/javascript"></script>
<script src="javascripts/DV/events/navigation.js" type="text/javascript"></script>
<script src="javascripts/DV/helpers/helpers.js" type="text/javascript"></script>
<script src="javascripts/DV/helpers/annotations.js" type="text/javascript"></script>
<script src="javascripts/DV/helpers/construction.js" type="text/javascript"></script>
<script src="javascripts/DV/helpers/editor.js" type="text/javascript"></script>
<script src="javascripts/DV/helpers/navigation.js" type="text/javascript"></script>
<script src="javascripts/DV/helpers/search.js" type="text/javascript"></script>
<script src="javascripts/DV/states/states.js" type="text/javascript"></script>
<script src="javascripts/DV/controllers/document_viewer.js" type="text/javascript"></script>
<script src="javascripts/DV/controllers/api.js" type="text/javascript"></script>
<script src="assets/templates.js" type="text/javascript"></script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32882277-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>

<div align = "center">
<h1>Welcome to the Star of the West Archive</h1>

<p>The Star of the West was a Bahá'í periodical which began publication on March 21, 1910 and ended publication under this title in March 1935.
The periodical featured translations of some Tablets of 'Abdu'l-Bahá and writings from Shoghi Effendi along with sharing news of the Bahá'í world.
The text was mostly in English, but also often offered a Persian language section with its own content.
<i>From Wikipedia, the free encyclopedia</i></p>

<center> <img src = /images/local/starquote.gif> </center>
<hr>
<h2>Select the volume you would like to read or to search </h2>
<form action="">
	<div>
    <select id="volumeSelect">
        <? for($i = 1;$i < 26; $i++) { ?>
        <option value="Vol<?= str_pad((int) $i,2,"0",STR_PAD_LEFT) ?>">Volume <?= $i ?>, 19<?= $i+9 ?> - 19<?= $i+10 ?></option>
        <? } ?>
	</select>
	<input type="button" id="buttonSelect" value="Select here" >
	</div>
</form>
<p>When you have finished with one volume, use your browser's back button to return to this page to select another volume. </p>
<hr>
<h2>A more flexible search engine</h2>
<p>You may wish to try a more flexible and powerful<a href=search.php> search engine</a>. You may wish to consult the <a href="instructions.php"> detailed instructions</a>.</p>
<hr>	
<h2>Searchable PDF files</h2>
<p>The following searchable PDF files are also available. If you open them with a PDF reader, you will be able to use the reader's search function. You may also be able to download the files to an eReader.</p>
<a href= "searchable_pdfs/SotW_Vol-01 (Mar 1910)-Vol-10 (Mar 1919).pdf"> Volumes 1 to 10 (202 Mb)</a>
<br>	<a href= "searchable_pdfs/SotW_Vol-11 (Mar 1920)-Vol-20 (Mar 1930).pdf"> Volumes 11 to 20 (317 Mb)</a>
<br>	<a href= "searchable_pdfs/SotW_Vol-21 (Apr 1930)-Vol-25 (Mar 1935).pdf"> Volumes 21 to 25 (177 Mb)</a>
<hr>

	<div><i>
	<p><b>Disclaimer: </b>The contents of this web site are not considered authoritative writings of the Bahá'í Faith, and are presented to aid both scholarly and historical research. This web site is the work of individuals and not under the purview of any institution of the Bahá'í Faith. Comments and suggestions are welcome at 
	<a href= "mailto: julian@lebensold.ca?subject=Feedback from starofthewest.info" > julian@lebensold.ca</a></p>
	</i>
	</div>
<div>
<!- PayPal donations-->
<p><i>If you would like to help defray the cost of hosting this website, please use this PayPal button:</i>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="69CPPQTJSZR5S">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>

</div>
</div>
<script type="text/javascript">

// starting volume
var current_volume = "Vol01";

// once the page is fully loaded, run what's here:
$(function(){
  // on button click, run the following:
  $("#buttonSelect").click(function(){
    //get the value of the currently selected volume:
    var vol =  $("#volumeSelect").val();
	current_volume = vol;
	// Go to the viewer page
	// use the name of the window to pass the parameter
	window.name = current_volume;
	location.href = 'viewer.erb';
	    })
});
// GLOBALS:
var sotw_config = {};

</script>

</body>
</html>
